import { ubyte } from '@bellatrix/appium/types';

export class VirtualKeyCode {
    static readonly LBUTTON: ubyte = 0x01 // Left mouse button
    static readonly RBUTTON: ubyte = 0x02 // Right mouse button
    static readonly CANCEL: ubyte = 0x03 // Control-break processing
    static readonly MBUTTON: ubyte = 0x04 // Middle mouse button
    static readonly XBUTTON1: ubyte = 0x05 // X1 mouse button
    static readonly XBUTTON2: ubyte = 0x06 // X2 mouse button

    static readonly BACK: ubyte = 0x08 // BACKSPACE key
    static readonly TAB: ubyte = 0x09 // TAB key

    static readonly CLEAR: ubyte = 0x0C // CLEAR key
    static readonly RETURN: ubyte = 0x0D // ENTER key

    static readonly SHIFT: ubyte = 0x10 // SHIFT key
    static readonly CONTROL: ubyte = 0x11 // CTRL key
    static readonly MENU: ubyte = 0x12 // ALT key
    static readonly PAUSE: ubyte = 0x13 // PAUSE key
    static readonly CAPITAL: ubyte = 0x14 // CAPS LOCK key
    static readonly KANA: ubyte = 0x15 // IME Kana mode
    static readonly HANGUL: ubyte = 0x15 // IME Hangul mode
    static readonly IME_ON: ubyte = 0x16 // IME On
    static readonly JUNJA: ubyte = 0x17 // IME Junja mode
    static readonly FINAL: ubyte = 0x18 // IME final mode
    static readonly HANJA: ubyte = 0x19 // IME Hanja mode
    static readonly KANJI: ubyte = 0x19 // IME Kanji mode
    static readonly IME_OFF: ubyte = 0x1A // IME Off
    static readonly ESCAPE: ubyte = 0x1B // ESC key
    static readonly CONVERT: ubyte = 0x1C // IME convert
    static readonly NONCONVERT: ubyte = 0x1D // IME nonconvert
    static readonly ACCEPT: ubyte = 0x1E // IME accept
    static readonly MODECHANGE: ubyte = 0x1F // IME mode change request
    static readonly SPACE: ubyte = 0x20 // SPACEBAR
    static readonly PRIOR: ubyte = 0x21 // PAGE UP key
    static readonly NEXT: ubyte = 0x22 // PAGE DOWN key
    static readonly END: ubyte = 0x23 // END key
    static readonly HOME: ubyte = 0x24 // HOME key
    static readonly LEFT: ubyte = 0x25 // LEFT ARROW key
    static readonly UP: ubyte = 0x26 // UP ARROW key
    static readonly RIGHT: ubyte = 0x27 // RIGHT ARROW key
    static readonly DOWN: ubyte = 0x28 // DOWN ARROW key
    static readonly SELECT: ubyte = 0x29 // SELECT key
    static readonly PRINT: ubyte = 0x2A // PRINT key
    static readonly EXECUTE: ubyte = 0x2B // EXECUTE key
    static readonly SNAPSHOT: ubyte = 0x2C // PRINT SCREEN key
    static readonly INSERT: ubyte = 0x2D // INS key
    static readonly DELETE: ubyte = 0x2E // DEL key
    static readonly HELP: ubyte = 0x2F // HELP key
    static readonly ZERO: ubyte = 0x30 // 0 key
    static readonly ONE: ubyte = 0x31 // 1 key
    static readonly TWO: ubyte = 0x32 // 2 key
    static readonly THREE: ubyte = 0x33 // 3 key
    static readonly FOUR: ubyte = 0x34 // 4 key
    static readonly FIVE: ubyte = 0x35 // 5 key
    static readonly SIX: ubyte = 0x36 // 6 key
    static readonly SEVEN: ubyte = 0x37 // 7 key
    static readonly EIGHT: ubyte = 0x38 // 8 key
    static readonly NINE: ubyte = 0x39 // 9 key

    static readonly A: ubyte = 0x41 // A key
    static readonly B: ubyte = 0x42 // B key
    static readonly C: ubyte = 0x43 // C key
    static readonly D: ubyte = 0x44 // D key
    static readonly E: ubyte = 0x45 // E key
    static readonly F: ubyte = 0x46 // F key
    static readonly G: ubyte = 0x47 // G key
    static readonly H: ubyte = 0x48 // H key
    static readonly I: ubyte = 0x49 // I key
    static readonly J: ubyte = 0x4A // J key
    static readonly K: ubyte = 0x4B // K key
    static readonly L: ubyte = 0x4C // L key
    static readonly M: ubyte = 0x4D // M key
    static readonly N: ubyte = 0x4E // N key
    static readonly O: ubyte = 0x4F // O key
    static readonly P: ubyte = 0x50 // P key
    static readonly Q: ubyte = 0x51 // Q key
    static readonly R: ubyte = 0x52 // R key
    static readonly S: ubyte = 0x53 // S key
    static readonly T: ubyte = 0x54 // T key
    static readonly U: ubyte = 0x55 // U key
    static readonly V: ubyte = 0x56 // V key
    static readonly W: ubyte = 0x57 // W key
    static readonly X: ubyte = 0x58 // X key
    static readonly Y: ubyte = 0x59 // Y key
    static readonly Z: ubyte = 0x5A // Z key

    static readonly LWIN: ubyte = 0x5B // Left Windows key
    static readonly RWIN: ubyte = 0x5C // Right Windows key
    static readonly APPS: ubyte = 0x5D // Applications key

    static readonly SLEEP: ubyte = 0x5F // Computer Sleep key
    static readonly NUMPAD0: ubyte = 0x60 // Numeric keypad 0 key
    static readonly NUMPAD1: ubyte = 0x61 // Numeric keypad 1 key
    static readonly NUMPAD2: ubyte = 0x62 // Numeric keypad 2 key
    static readonly NUMPAD3: ubyte = 0x63 // Numeric keypad 3 key
    static readonly NUMPAD4: ubyte = 0x64 // Numeric keypad 4 key
    static readonly NUMPAD5: ubyte = 0x65 // Numeric keypad 5 key
    static readonly NUMPAD6: ubyte = 0x66 // Numeric keypad 6 key
    static readonly NUMPAD7: ubyte = 0x67 // Numeric keypad 7 key
    static readonly NUMPAD8: ubyte = 0x68 // Numeric keypad 8 key
    static readonly NUMPAD9: ubyte = 0x69 // Numeric keypad 9 key
    static readonly MULTIPLY: ubyte = 0x6A // Multiply key
    static readonly ADD: ubyte = 0x6B // Add key
    static readonly SEPARATOR: ubyte = 0x6C // Separator key
    static readonly SUBTRACT: ubyte = 0x6D // Subtract key
    static readonly DECIMAL: ubyte = 0x6E // Decimal key
    static readonly DIVIDE: ubyte = 0x6F // Divide key
    static readonly F1: ubyte = 0x70 // F1 key
    static readonly F2: ubyte = 0x71 // F2 key
    static readonly F3: ubyte = 0x72 // F3 key
    static readonly F4: ubyte = 0x73 // F4 key
    static readonly F5: ubyte = 0x74 // F5 key
    static readonly F6: ubyte = 0x75 // F6 key
    static readonly F7: ubyte = 0x76 // F7 key
    static readonly F8: ubyte = 0x77 // F8 key
    static readonly F9: ubyte = 0x78 // F9 key
    static readonly F10: ubyte = 0x79 // F10 key
    static readonly F11: ubyte = 0x7A // F11 key
    static readonly F12: ubyte = 0x7B // F12 key
    static readonly F13: ubyte = 0x7C // F13 key
    static readonly F14: ubyte = 0x7D // F14 key
    static readonly F15: ubyte = 0x7E // F15 key
    static readonly F16: ubyte = 0x7F // F16 key
    static readonly F17: ubyte = 0x80 // F17 key
    static readonly F18: ubyte = 0x81 // F18 key
    static readonly F19: ubyte = 0x82 // F19 key
    static readonly F20: ubyte = 0x83 // F20 key
    static readonly F21: ubyte = 0x84 // F21 key
    static readonly F22: ubyte = 0x85 // F22 key
    static readonly F23: ubyte = 0x86 // F23 key
    static readonly F24: ubyte = 0x87 // F24 key

    static readonly NUMLOCK: ubyte = 0x90 // NUM LOCK key
    static readonly SCROLL: ubyte = 0x91 // SCROLL LOCK key

    static readonly LSHIFT: ubyte = 0xA0 // Left SHIFT key
    static readonly RSHIFT: ubyte = 0xA1 // Right SHIFT key
    static readonly LCONTROL: ubyte = 0xA2 // Left CONTROL key
    static readonly RCONTROL: ubyte = 0xA3 // Right CONTROL key
    static readonly LMENU: ubyte = 0xA4 // Left ALT key
    static readonly RMENU: ubyte = 0xA5 // Right ALT key
    static readonly BROWSER_BACK: ubyte = 0xA6 // Browser Back key
    static readonly BROWSER_FORWARD: ubyte = 0xA7 // Browser Forward key
    static readonly BROWSER_REFRESH: ubyte = 0xA8 // Browser Refresh key
    static readonly BROWSER_STOP: ubyte = 0xA9 // Browser Stop key
    static readonly BROWSER_SEARCH: ubyte = 0xAA // Browser Search key
    static readonly BROWSER_FAVORITES: ubyte = 0xAB // Browser Favorites key
    static readonly BROWSER_HOME: ubyte = 0xAC // Browser Start and Home key
    static readonly VOLUME_MUTE: ubyte = 0xAD // Volume Mute key
    static readonly VOLUME_DOWN: ubyte = 0xAE // Volume Down key
    static readonly VOLUME_UP: ubyte = 0xAF // Volume Up key
    static readonly MEDIA_NEXT_TRACK: ubyte = 0xB0 // Next Track key
    static readonly MEDIA_PREV_TRACK: ubyte = 0xB1 // Previous Track key
    static readonly MEDIA_STOP: ubyte = 0xB2 // Stop Media key
    static readonly MEDIA_PLAY_PAUSE: ubyte = 0xB3 // Play/Pause Media key
    static readonly LAUNCH_MAIL: ubyte = 0xB4 // Start Mail key
    static readonly LAUNCH_MEDIA_SELECT: ubyte = 0xB5 // Select Media key
    static readonly LAUNCH_APP1: ubyte = 0xB6 // Start Application 1 key
    static readonly LAUNCH_APP2: ubyte = 0xB7 // Start Application 2 key

    static readonly OEM_1: ubyte = 0xBA // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ;: key
    static readonly OEM_PLUS: ubyte = 0xBB // For any country/region, the + key
    static readonly OEM_COMMA: ubyte = 0xBC // For any country/region, the , key
    static readonly OEM_MINUS: ubyte = 0xBD // For any country/region, the - key
    static readonly OEM_PERIOD: ubyte = 0xBE // For any country/region, the . key
    static readonly OEM_2: ubyte = 0xBF // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the /? key
    static readonly OEM_3: ubyte = 0xC0 // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the `~ key
    static readonly OEM_4: ubyte = 0xDB // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the [{ key
    static readonly OEM_5: ubyte = 0xDC // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the \| key
    static readonly OEM_6: ubyte = 0xDD // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ]} key
    static readonly OEM_7: ubyte = 0xDE // Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '" key
    static readonly OEM_8: ubyte = 0xDF // Used for miscellaneous characters; it can vary by keyboard.
    static readonly OEM_102: ubyte = 0xE2 // The <> keys on the US standard keyboard, or the \| key on the non-US 102-key keyboard
    static readonly PROCESSKEY: ubyte = 0xE5 // IME PROCESS key
    static readonly PACKET: ubyte = 0xE7 // Used to pass Unicode characters as if they were keystrokes. The PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP
    static readonly ATTN: ubyte = 0xF6 // Attn key
    static readonly CRSEL: ubyte = 0xF7 // CrSel key
    static readonly EXSEL: ubyte = 0xF8 // ExSel key
    static readonly EREOF: ubyte = 0xF9 // Erase EOF key
    static readonly PLAY: ubyte = 0xFA // Play key
    static readonly ZOOM: ubyte = 0xFB // Zoom key
    static readonly NONAME: ubyte = 0xFC // Reserved
    static readonly PA1: ubyte = 0xFD // PA1 key
    static readonly OEM_CLEAR: ubyte = 0xFE // Clear key
}