# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.6
      uses: actions/setup-node@v4
      with:
        node-version: 20.6
        cache: 'npm'
    - run: ls
    - run: npm ci
      working-directory: example
    - run: npm test
